implementation of the RCS platform, using React, Vite, and Tailwind CSS
arielsepton/platform-frontend pull request #1
Opened 2024-05-21 12:20 UTC by arielsepton

## Description
This PR introduces the initial implementation of the RCS platform, using React, Vite, and Tailwind CSS. 

## Changes made
### Components Added
* Base Components:
  * Typography: Added Typography component for consistent text styling.
  * Modal: Dynamic Modal component.
  * Button: Dynamic Button component to handle various styles dynamically.
* Form Components:
  * Input: Created Input component for form input fields.
* Header Components:
  * Header: Implemented Header component.
  * Breadcrumb: Added Breadcrumb component for hierarchical navigation within pages.
* Login Components:
  * Login Input: Added Login Input component for login form fields.
* Sidebar Components:
  * Sidebar: Implemented Sidebar component for navigation menu.
  * Sidebar Item: Added Sidebar Item component for individual navigation items within the Sidebar.

### Styling and Theming
* Red Hat Fonts: Integrated Red Hat Fonts.

### Testing
* Component Testing: Implemented Cypress component tests for all newly created components.

![image](https://github.com/dana-team/platform-frontend/assets/64063409/c45ec09c-7f4d-4add-93ce-edef7c301937)
![image](https://github.com/dana-team/platform-frontend/assets/64063409/ca2b8731-14f4-41da-a75e-7bab8aa46a90)
![image](https://github.com/dana-team/platform-frontend/assets/64063409/9a55d395-c2a9-47ee-9765-89652e9a3536)

![image](https://github.com/dana-team/platform-frontend/assets/64063409/1ac3cf0c-0b69-4915-8faa-b991779f047d)
![image](https://github.com/dana-team/platform-frontend/assets/64063409/58ef2534-8674-470b-bf7d-33d664294cb1)
![image](https://github.com/dana-team/platform-frontend/assets/64063409/d8b2d470-2949-4017-be8c-5a146070b2b9)
![image](https://github.com/dana-team/platform-frontend/assets/64063409/0920d297-5b6b-4e59-a5b9-b1a69a73935a)
![image](https://github.com/dana-team/platform-frontend/assets/64063409/106dc03e-d3af-469e-85a3-3e81bd1f7c7a)
![image](https://github.com/dana-team/platform-frontend/assets/64063409/c88ca3e6-c980-47ab-9134-fe6d57ea807e)
![image](https://github.com/dana-team/platform-frontend/assets/64063409/d6f868c1-530b-4de1-abbc-a89fd4c9bed3)

2024-05-21 14:38 UTC, danielsinai requested changes
Wow 👑 
Small nonsense comments :)

2024-05-21 14:38 UTC, danielsinai commented on cypress/fixtures/example.json
> +{
I guess thsi file can be deleted  as it's just an example from the bootstraping of cypress no?

2024-05-21 14:38 UTC, danielsinai commented on cypress/support/commands.ts
> +/// <reference types="cypress" />
Same can we delete this one?

2024-05-21 14:38 UTC, danielsinai commented on src/Pages/Login/Login.tsx
> +    // TODO: perhaps create "useAuth" hook and call it here.
do it :))

2024-05-21 14:38 UTC, danielsinai commented on src/Pages/Login/Login.tsx
> +    // TODO: perhaps create "useAuth" hook and call it here.
sounds good

2024-05-21 14:38 UTC, danielsinai commented on src/Pages/Login/Login.tsx
> +/// <reference types="vite-plugin-svgr/client" />
Consider using a library for handling forms. It should make your life easier https://www.react-hook-form.com/

2024-05-21 14:38 UTC, danielsinai commented on src/Components/Login/Input/LoginInput.tsx
> +const LoginInput: React.FC<LoginInputProps> = ({
I believe `LoginInput` should not exist, and only variants of the `Input` it self should. WDYT

2024-05-21 14:38 UTC, danielsinai commented on src/Pages/Login/Login.tsx
> +  const [usernameError, setUsernameError] = useState("");
If you will use a lib, you will probably won't need this state parameters of errors

2024-05-21 14:38 UTC, danielsinai commented on src/Components/Typography/Typography.tsx
> +import { variantStyles } from "./VariantStyles";
Use camelCase for folders and non-component file name and PascalCase for component file and interface file.

2024-05-21 14:38 UTC, danielsinai commented on src/Components/Typography/Typography.tsx
> +import { variantStyles } from "./VariantStyles";
I wrtie it here once, but I think that shoould be applied all through the project.

2024-05-21 14:38 UTC, danielsinai commented on src/Components/Typography/Typography.tsx
> +  tag: Tag = "p",
a common name for the is `as` becaue you use typography as a div, as a span etc

2024-05-21 14:38 UTC, danielsinai commented on src/Components/Header/Header.tsx
> +            children={
You don't need to mention `children`, just pass it as children :)  as children is a safe word in react
i.e 
```
<Typography>
{APP_NAME}
</Typography>
```

2024-05-21 14:38 UTC, danielsinai commented on src/Components/Header/Header.tsx
> +    const importComponent = async () => {
That's a good solution, but you can also just make a map from the color to the component. WDYT?

2024-05-21 14:38 UTC, danielsinai commented on src/Components/Form/Input/Input.tsx
> +      {type === "password" && inputValue && (
I think we can beautify it, maybe some sort of mapping between to the type actualy render type instead

2024-05-21 14:38 UTC, danielsinai commented on src/Components/Form/Input/Input.tsx
> +  onChange: (value: any) => void;
Don't use `any`. If you don't know that type preferably use `uknown` the reason is that when using `any` you are risking yourself to access to unsafe varaibles.
The best solution here is to use T (Typescript generics)

2024-05-21 14:38 UTC, danielsinai commented on src/Components/Sidebar/Sidebar.tsx
> +  const toggleSidebar = () => {
use `useCallback`, because if not, every rerender of this component the funciton would be recreated for no reasson

2024-05-21 14:38 UTC, danielsinai commented on src/Components/Button/ButtonStyles.ts
> +  link: "hover:underline hover:underline-offset-8 hover:decoration-green/basic-6",
Is link really a variriant?

2024-05-21 14:38 UTC, danielsinai commented on src/Components/Button/Button.tsx
> +      {icon && (iconPosition === "top" || iconPosition === "left") && (
What If I do right top? not sure I exactly gets how it works

2024-05-21 21:47 UTC, arielsepton commented on src/Components/Login/Input/LoginInput.tsx
> +const LoginInput: React.FC<LoginInputProps> = ({
Agree

2024-05-21 21:52 UTC, arielsepton commented on src/Components/Button/Button.tsx
> +      {icon && (iconPosition === "top" || iconPosition === "left") && (
I Think top/bottom/left/right should cover most cases, corner icons might be an overkill. WDYT?

2024-05-21 21:54 UTC, arielsepton commented on src/Components/Button/ButtonStyles.ts
> +  link: "hover:underline hover:underline-offset-8 hover:decoration-green/basic-6",
It is actually

2024-06-15 13:40 UTC, danielsinai requested changes
🦢 Really great work, professional

2024-06-15 13:40 UTC, danielsinai commented on .github/workflows/ci.yml
> +  build:
This made me thinking maybe it worth to create `Dockerfile` and also validate ehre that it builts successfully

2024-06-15 13:40 UTC, danielsinai commented on .github/workflows/ci.yml
> +    runs-on: ubuntu-22.04
Any reason why is that one `ubuntu-22.04` and the other are latest? 🤔

2024-06-15 13:40 UTC, danielsinai commented on index.html
> -<!DOCTYPE html>
I am not sure that's possible buit I would consider using this file instead of the `cypress/support/component-index.html`.

2024-06-15 13:40 UTC, danielsinai commented on .github/workflows/ci.yml
> +        run: npm install
Use `npm ci` instead of `npm install`

2024-06-15 13:40 UTC, danielsinai commented on src/App.tsx
> +  context: { isAuthenticated: undefined! },
`undefined!` means this is not undefined but it's actually is, is it required? can we fix it somehow?

2024-06-15 13:40 UTC, danielsinai commented on src/TestRouter.tsx
> +import {
Cool mock!
Can we move it out from the `src/` dir? maybe a new or existing directory that fits more for testing?

2024-06-15 13:40 UTC, danielsinai commented on src/common/consts.ts
> +export const API_URL = "https://example.com";
Probably better to use [env variables of vite](https://vitejs.dev/guide/env-and-mode)

2024-06-15 13:40 UTC, danielsinai commented on src/components/button/buttonStyles.ts
> +  "primary-onPress": primaryButtonTypography,
Can you explain me the pattern with the `onPress`? meaning - would you expect thatthe variant as a whole would change freom the outside?

I believe it's better to use `tailwind` features for that `active:bg-nice`

2024-06-15 13:40 UTC, danielsinai commented on src/components/container/Container.tsx
> +  children?: ReactNode;
Optional? can a container not have a children?

2024-06-15 13:40 UTC, danielsinai commented on src/components/container/Container.tsx
> +const Container: React.FC<ContainerProps> = React.memo(
IMO we need to find another name to `Container` as it's too general purpose - do you have any idea?

2024-06-15 13:40 UTC, danielsinai commented on src/components/form/input/Input.tsx
> +const typeToToggleMap: { [key: string]: ToggleComponent } = {
Nice! 
But isn't too complicate? maybe preferably do it a bit more `KIS` and just have another `ShowHideInput`.. Not really sure on this comment - to your judgment

2024-06-15 13:40 UTC, danielsinai commented on src/components/form/input/Input.tsx
> +            placeholder={placeholder}
`...props` is instead of paceholder=placeholder right?
Also `ref`

2024-06-15 13:40 UTC, danielsinai commented on src/components/form/input/Input.tsx
> +const typeToToggleMap: { [key: string]: ToggleComponent } = {
Anyway I would maybe transfer it into a different file

2024-06-15 13:40 UTC, danielsinai commented on src/components/header/Header.tsx
> +  const getFirstLetter: () => string = useCallback(() => {
Probably better to define such functions as outside util, it's a really generic function

2024-06-15 13:40 UTC, danielsinai commented on src/components/header/Header.tsx
> +          onClick={async () => {
It's better to encapsulate the `router.invalidate()` inside the `signOut` function, as everytime you would signOut you would like it to happen (I guess)

2024-06-15 13:40 UTC, danielsinai commented on src/components/header/Header.tsx
> +function DynamicLoader(thumbnail: number) {
Cool generic component that should (I believe) be outside of the `Header` componet

2024-06-15 13:40 UTC, danielsinai commented on src/components/header/Header.tsx
> +          onClick={async () => {
Also why is it async?

2024-06-15 13:40 UTC, danielsinai commented on src/pages/projects/Projects.tsx
> +  const [breadcrumbs] = useState(generateBreadcrumbs(currentPath));
This should not be a useState. Make it a `useMemo`

2024-06-15 13:40 UTC, danielsinai commented on src/pages/projects/Projects.tsx
> +  const [breadcrumbs] = useState(generateBreadcrumbs(currentPath));
Actually useState might also fit here, but it's weird bvecause you never setIt, and if someone will use this code he might change that and cause a lot of rerenders as it's an object

2024-06-15 13:40 UTC, danielsinai commented on src/components/header/breadcrumb/Breadcrumb.tsx
> +const Breadcrumb = React.memo(({ breadcrumb }: BreadcrumbProps) => (
NIce `React.memo` 😍 
Probably better to use primitivse here to make sure no rerenders are happpening for no reason

2024-06-15 13:40 UTC, danielsinai commented on src/components/header/breadcrumb/generateBreadcrumbs.ts
> +    breadcrumbs.push({ text: pathSegments[1], isDropdown: true });
Personally (but it's totally up to you) I never use `push` as this function mutates the original array, meaning if someone reads this code he needs to fully understand the flow to guess the final state.

Prefereably I would use `.map` + `.filter`

2024-06-15 13:40 UTC, danielsinai commented on src/components/modal/Modal.tsx
> +  const handleKeyPress = (e: KeyboardEvent) => {
`useCallback` probably. 
It will make sure the function won't be recreated everytime

2024-06-15 13:40 UTC, danielsinai commented on src/components/sidebar/Sidebar.tsx
> +      setIsSidebarExpanded(!isSidebarExpanded);
Would be better to remove this fucntion and do
```
setIsSidebarExpanded((prev) => !prev)
```

2024-06-15 13:40 UTC, danielsinai commented on src/pages/login/Login.tsx
> +  const { mutateInstance: mutate } = useDataMutation<User>("/auth", undefined, {
Writing it once, I believe it should to apply to all the `useDataMutations`
Worth adding another hook, which is simpler - that's called `useLogin` and encapsulate the logic in it- in the future dataMutations would be happening from various places in the app

2024-06-15 13:40 UTC, danielsinai commented on src/pages/login/Login.tsx
> +  const { mutateInstance: mutate } = useDataMutation<User>("/auth", undefined, {
Think about `useAuth`, it's reallty similar

2024-06-15 17:44 UTC, danielsinai approved these changes

2024-06-15 17:47 UTC, merged